name: Discord Notification

on:
  push:
    branches:
      - '**'  # Isso ativa para push em qualquer branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            📢 Novo push feito por **${{ github.actor }}**
            🔀 Branch: `${{ github.ref }}`
            🔧 Commit: `${{ github.sha }}`
            📄 Mensagem: ${{ github.event.head_commit.message }}
