<<<<<<< HEAD
name: Notificação de Alteração no Repositório
=======
name: Notificar Alterações no GitHub para o Discord
>>>>>>> 9ced1a80f073da6453b9b07ac3036dd856863b58

on:
  push:
    branches:
<<<<<<< HEAD
      - '*'  # Notifica em qualquer alteração em qualquer branch...

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            "🚨 *Novo Commit* no repositório!"
            "\n**Autor**: ${{ github.actor }}"
            "\n**Mensagem do Commit**: ${{ github.event.head_commit.message }}"
            "\n**Data e Hora do Commit**: ${{ github.event.head_commit.timestamp }}"
            "\n**Commit Hash**: ${{ github.sha }}"
            "\n**Branch**: ${{ github.ref_name }}"  # Exibe o nome da branch
            "\n\nAcesse o commit completo: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
=======
      - main  # Ou qualquer outra branch que você queira monitorar
  pull_request:
    types: [opened, closed, merged]  # Você pode ajustar conforme o tipo de PR que deseja monitorar

Discord:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Discord
        uses: rjstone/discord-webhook-notify@v1  # Essa ação envia a notificação para o Discord
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}  # Usando o segredo do webhook do Discord
          severity: info  # Tipo de severidade da mensagem (pode ser info, warning, etc.)
>>>>>>> 9ced1a80f073da6453b9b07ac3036dd856863b58
