name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord:
    name: Enviar alerta para o Discord
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem via Discord Webhook
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}  # Certifique-se de configurar o segredo no GitHub
          content: "📢 Um novo commit foi feito no branch main!"
