name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enviar alerta para Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "📣 Novo commit enviado para o branch main!"
