name: Testes Automatizados

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Certifique-se de que o pytest seja instalado

    - name: Executar testes
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Rodando os testes
