name: Testes Automatizados

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Certifique-se de ter o arquivo requirements.txt com as dependências necessárias

    - name: Executar testes
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Você pode personalizar essa linha, mas esse comando ajuda a parar após o primeiro erro, desativa alertas e gera uma saída mais limpa
